spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.1"

loans:
  message: "Welcome to the loans qa"
  contactDetails:
    name: "John"
    email: "john@john"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1345
